### PR TITLE
Add most of pods as spm packages

### PR DESCRIPTION
**Pull request by vilunov**

### CODE REVIEW

**Comment by tmolitor-stud-tu** [comment]
I will only merge this once cocoapods are eliminated completely

**Comment by tmolitor-stud-tu** [comment]
Hey @vilunov, do you plan to continue working on this and move the missing packages to SPM, too?

**Comment by vilunov** [comment]
@tmolitor-stud-tu hey, I'm taking a break until February, sorry. Feel free to close this, I'll reopen it when I'm more ready.

**Comment by tmolitor-stud-tu** [comment]
are you still planning to work on this?

**Comment by tmolitor-stud-tu** [comment]
I'm closing this now, feel free to reopen it :)

**Pull request closed without merging**
