### PR TITLE
adding swift emoji handling

### PR DESCRIPTION
**Pull request by anurodhp**
There is a separate project to allow xcode to genereate the bridging
header which will not work when there are mutiple targets

### CODE REVIEW

**Comment by FriedrichAltheide** [comment]
reverted this PR/removed the commit from develop. I added the new emoji handling without the use of a separate project in cf7ae69a0507ceee7a1d268f4425fe94d13f8faf

**Comment by anurodhp** [comment]
Oh cool looks like the Xcode bug is fixed

**Comment by anurodhp** [comment]
Actually mlcrypto only exists to get around the Xcode bug too and can be brought into the main project

**Comment by tmolitor-stud-tu** [comment]
As far as i know Friedrich did this already, too

Am 30. März 2021 23:19:27 MESZ schrieb Anu Pokharel ***@***.***>:

**Comment by anurodhp** [comment]
fantastic, thank you.

**Comment by tmolitor-stud-tu** [comment]
what xcode version are you using?

**Comment by anurodhp** [comment]
current. It was an issue in 2019 and i havent actually looked at it since

**Pull request merged**
