### PR TITLE
Travis: Update OSX image version to 12.2 And fix crash on nil 

### PR DESCRIPTION
**Pull request by anurodhp**

### CODE REVIEW

**Comment by anurodhp** [comment]
Travis: Update OSX image version to 12.2 and fix nil crash

**Review by tmolitor-stud-tu — CHANGES_REQUESTED** [review]
Commit https://github.com/monal-im/Monal/pull/570/commits/9d79733e8179ad2d37074f564dab6778b2e30da0
is not akready in our develop branch, please cherry-pick the travis fixes from develop if you need them, instead of writing new ones that will impose merge conflicts later on

**Comment by anurodhp** [comment]
updated with the commit from develop

**Comment by tmolitor-stud-tu** [comment]
perfect, can you do a rebase and remove the commit rather than reverting it to not clutter the history unnecessary?

**Comment by FriedrichAltheide** [comment]
Please cherry-pick my travis commit instead of adding it as a new commit

**Comment by anurodhp** [comment]
Ugh trying to do this on a new device. Doing odd stuff.

**Review by FriedrichAltheide — APPROVED** [review]

**Review by tmolitor-stud-tu — APPROVED** [review]

**Pull request merged**
