### PR TITLE
Appstore text - RO

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by tmolitor-stud-tu** [comment]
This is missing the other files

**Comment by licaon-kter** [comment]
I wasn't sure about them being needed. Thanks

**Comment by tmolitor-stud-tu** [comment]
Apparently the correct language code would be "ro", not "ro-RO".

Taken from here:
- https://github.com/fastlane/fastlane/issues/16625#issuecomment-658181756
- https://github.com/fastlane/fastlane/issues/16625#issue-640591002

**Comment by licaon-kter** [comment]
No experience with Apple.

That's how Google has it :shrug:

**Comment by tmolitor-stud-tu** [comment]
I did not know this, too, but it threw an error when I tried to upload it to the appstore, so I started to research what apple might like as RO "name" :D

**Pull request merged**
