### PR TITLE
Patch 4.9.2

### PR DESCRIPTION
**Pull request by tmolitor-stud-tu**
Monal 4.9.2 cherry-picks

### CODE REVIEW

**Comment by FriedrichAltheide** [comment]
I think we should add these commits as well
https://github.com/monal-im/Monal/commit/a1f3a7a6fdb31da5300387b5407c83386dcd30c6
https://github.com/monal-im/Monal/commit/64965946bbe45e07f69c2e8aa4207529e5fe8f5a
https://github.com/monal-im/Monal/commit/5adff0f67acdd70f36551af935215970171a5ef4

**Comment by tmolitor-stud-tu** [comment]
@FriedrichAltheide just cherry-pick them in here :)

**Review by FriedrichAltheide — APPROVED** [review]

**Review by anurodhp — APPROVED** [review]

**Comment by tmolitor-stud-tu** [comment]
@anurodhp you forgot to add your commits first?? Wasn't that the reason to create a 4.9.2 in the first place?

**Comment by tmolitor-stud-tu** [comment]
I mean this one: https://github.com/monal-im/Monal/commit/50e74bb6c83322c0267dad4d29fa8c51101f6a10

**Pull request merged**
